### ISSUE TITLE
normalise_obj.py input structure?

### ISSUE THREAD

**Issue by txree** [LexSong/earth-reverse-engineering-utils#1]
Not sure how to structure the input for 'normalise_obj.py'
Is the path to the .obj included in the string like "python normalise_obj.py [path]" and then saved in the same folder with a ".2" suffix?

**Comment by LexSong** [comment]
Let me check it... I haven't used this script for a while.

The command format is:

    python normalize_obj.py X Y Z OBJ_PATH
    
XYZ is the reference point. It would be the origin (0, 0, 0) after normalization.

The script assumes that the original obj is from Google Earth ECEF coordinate. (See https://en.wikipedia.org/wiki/ECEF)
Therefore, the script will also rotate the whole obj to normalize the vertical direction.

**Comment by txree** [comment]
That did it, thanks!
