### ISSUE TITLE
How to rotate the model in batches according to the geocentric coordinates without changing the position?

### ISSUE THREAD

**Issue by Zoren2022** [LexSong/earth-reverse-engineering-utils#2]
》In [normalize_obj.py](https://github.com/LexSong/earth-reverse-engineering/blob/testing/normalize_obj.py), the script normalize the mesh with a reference XYZ point instead of the mesh center. Therefore we could normalize several meshes with the same origin and keep their relative position. The script also rotate the mesh with latitude and longitude of the reference point, to align north/south and east/west axes.

PS:How to rotate the model in batches according to the geocentric coordinates without changing the position?

**Comment by LexSong** [comment]
Hi, I didn't touch this project for a while. However, it looks like that you already found the correct way to rotate the mesh in the following mails.

If my memory is correct, I didn't try to align the cardinal directions to any specific XYZ axis. It's up to the end user to do the final rotation to flip the mesh to the desired orientation.

I hope this will be helpful.
